### ISSUE TITLE
Can't add loans to basket on kiva.org with HTTPS-E enabled (5.0-development-2)

### ISSUE THREAD

**Issue by austin987** [EFForg/https-everywhere#1010]
Originally filed at https://trac.torproject.org/projects/tor/ticket/11645.

You'll need a kiva account for this. Once logged in, using FF 28.0 on Fedora 20, trying to add a loan to my account has no effect. Disabling HTTPS-E for kiva.org alone works around it.

Also present in Iceweasel 31.3.0, 5.0-development-2, debian jessie.

**Comment by StevenRoddis** [comment]
Hi @austin987 are you able to post the console output from Firefox when you try to add a loan?

**Comment by austin987** [comment]
Hi @StevenRoddis, there is no output at that time (and interestingly, iceweasel gives no outout at all, aside from the G-lib error.

There are some earlier messages, which I've attached. Do I need to enable logging somewhere first?

**Comment by austin987** [comment]
(process:5427): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
info: Error while loading localization: There is no localization file for your language.
error: An exception occurred.
Traceback (most recent call last):
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/l10n/loader.js:18", line 5, in readURI/request.onload
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:138", line 32, in resolve
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:32", line 43, in then
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:112", line 34, in resolved
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:138", line 32, in resolve
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:32", line 43, in then
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:112", line 34, in resolved
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:138", line 32, in resolve
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:32", line 43, in then
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:112", line 34, in resolved
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:138", line 32, in resolve
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:32", line 43, in then
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:112", line 34, in resolved
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:138", line 32, in resolve
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:32", line 43, in then
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:112", line 34, in resolved
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:138", line 32, in resolve
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:40", line 51, in then
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:113", line 35, in rejected
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:138", line 32, in resolve
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:32", line 43, in then
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:112", line 51, in resolved
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/promise.js:50", line 18, in effort
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/addon/runner.js:86", line 7, in onLocalizationReady
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/addon/runner.js:109", line 19, in run
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:281", line 10, in main
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:193", line 3, in load
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:167", line 19, in evaluate
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/privacyfix/lib/main.js:3", line 14, in 
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:267", line 14, in require
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:193", line 3, in load
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:167", line 19, in evaluate
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/addon-kit/lib/tabs.js:14", line 28, in 
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:267", line 14, in require
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:193", line 3, in load
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:167", line 19, in evaluate
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/addon-kit/lib/windows.js:19", line 23, in 
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:267", line 14, in require
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:193", line 3, in load
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:167", line 19, in evaluate
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/windows/dom.js:8", line 21, in 
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:267", line 14, in require
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:193", line 3, in load
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/loader.js:167", line 19, in evaluate
  File "resource://7ca9cf31-1c73-46cd-8377-85ab71ea771f/api-utils/lib/private-browsing/utils.js:19", line 3, in 
TypeError: Cc['@mozilla.org/privatebrowsing;1'] is undefined
1422950928599	GMPInstallManager.simpleCheckAndInstall	INFO	Last check was: 3774 seconds ago, minimum seconds: 86400
1422950928599	GMPInstallManager.simpleCheckAndInstall	INFO	Will not check for updates.

**Comment by StevenRoddis** [comment]
Hi @austin987 this should show you how to view the web console: https://developer.mozilla.org/en/docs/Tools/Web_Console

**Comment by austin987** [comment]
Ah, thanks for the link. Output:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the
remote resource at
http://api.mixpanel.com/track/?data=eyJldmVudCI6ICJjbGljayIsInByb3BlcnRpZXMiOiB7IiRvcyI6ICJMaW51eCIsIiRicm93c2VyIjogIkZpcmVmb3giLCIkc2NyZWVuX2hlaWdodCI6IDEwODAsIiRzY3JlZW5fd2lkdGgiOiAxOTIwLCJtcF9saWIiOiAid2ViIiwiJGxpYl92ZXJzaW9uIjogIjIuMy4yIiwiZGlzdGluY3RfaWQiOiAiMTQ5YmNjMWM4MWY0NDktMDU4NjRlMzhlNzNhNS0zZTA0NTk3Yi0xZmE0MDAtMTQ5YmNjMWM4MjA4YWQiLCJsb2dnZWRfaW4iOiB0cnVlLCJrdi1leHBlcmltZW50LkxvYW5DaGFubmVsQnJvd3NpbmcuTG93LnZlcnNpb24iOiAiYS1jb250cm9sIiwia3YtZXhwZXJpbWVudC5Mb2FuQ2FyZE9wdGltaXphdGlvbi5DYXRlZ29yeVBhZ2VzLnZlcnNpb24iOiAiYi1ncmlkLWxhcmdlLWNhcmQiLCJrdi1leHBlcmltZW50LkxvYW5DaGFubmVsQnJvd3NpbmcuSGlnaC52ZXJzaW9uIjogImEtY29udHJvbCIsImt2LWV4cGVyaW1lbnQuSGVscEZpbmRpbmdMb2FuLkhlbHBMaW5rLnZlcnNpb24iOiAiYi1saW5rIiwia3YtZXhwZXJpbWVudC5Mb2FuQ2FyZE9wdGltaXphdGlvbi5MZW5kVGFiLnZlcnNpb24iOiAiZC1kb2xsYXJzLXRvLWdvLW5vLWxvYW4tYW1vdW50Iiwia3YtZXhwZXJpbWVudC5PcHRpb25hbERvbmF0aW9uUHJvbXB0LlRleHQudmVyc2lvbiI6ICJnLXN1Z2dlc3RlZF9tYXR0ZXJzIiwia3YtZXhwZXJpbWVudC5XaXRoZHJhd2Fscy5SZXF1ZXN0LnZlcnNpb24iOiAiYi1kb25hdGlvbl9hcHBlYWwiLCJrdi11c2VyLW1lbWJlci1zaW5jZSI6ICIyMDEzLTAyLTE3VDAyOjI5OjMxWiIsImt2LXVzZXIteWVhcnMtb24ta2l2YSI6IDEsImt2LXVzZXItbG9hbi1jb3VudCI6IDk4LCJrdi1leHAuY2Fyb3VzZWwtdHlwZSI6ICJyZWNvbW1lbmRlZCIsImt2LWV4cC5raWxsLWhvbWUiOiAidW5kZWZpbmVkIiwia3YtZXhwLm5vLTI1IjogInVuZGVmaW5lZCIsImt2LWV4cC5ndWlkLWxlbmQtdjIiOiAidW5kZWZpbmVkIiwia3Ytc2F2ZWRfc2VhcmNoX2VuYWJsZWQiOiB0cnVlLCJrdi1lbGVtZW50IjogImxlbmQtbm93Iiwia3YtdXJsIjogIi9sZW5kIiwidG9rZW4iOiAiYjk4OTYyZWE3Y2I5ZGNmMmUyODE5ZGZjNzNkOWIwMjIifX0%3D&ip=1&_=1422990116909.
This can be fixed by moving the resource to the same domain or enabling
CORS.

On Tue, Feb 3, 2015 at 3:33 AM, Steven Roddis <notifications@github.com>
wrote:

> Hi @austin987 <https://github.com/austin987> this should show you how to
> view the web console:
> https://developer.mozilla.org/en/docs/Tools/Web_Console
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EFForg/https-everywhere/issues/1010#issuecomment-72619790>
> .
>



-- 
-Austin

**Comment by StevenRoddis** [comment]
@austin987 thanks for that, I'll test the website in the evening and hopefully find a fix.
Do you know if it was working in the 4.0.x releases?

**Comment by austin987** [comment]
@StevenRoddis, no. Bug was originally reported against 4.0-development-16.

**Comment by StevenRoddis** [comment]
I had a look today, it turns out rewriting `/ajax/addBasket` was the problem as it the site redirects it to `error.html`
https://github.com/EFForg/https-everywhere/blob/f1e935a454c57c50802d1fcfa1b69290498410ae/src/chrome/content/rules/Kiva.org.xml

`/ajax/` is explicitly excluded from being excluded using `?!` ie. negative lookahead.

I'm preparing a fix that prevents rewriting on /ajax/

**Comment by StevenRoddis** [comment]
This can be closed, as my PR has been merged.

**Comment by austin987** [comment]
Yep, works now, thanks Steven!
