### ISSUE TITLE
Issues with https-everywhere-rewriter

### ISSUE THREAD

**Issue by fuglede** [EFForg/https-everywhere#5137]
I don't seem to have much luck in using `rewriter.js`; #2926 mentions that it has been outdated at some point, but I noticed that it has had [an update](https://github.com/EFForg/https-everywhere/commit/db8ee9eceae497c78d7f9deabeebcecf31ad92af) since then. The first issue I'm seeing is

	~/https-everywhere/rewriter$ nodejs rewriter.js ~/repos/test/

	/home/fuglede/https-everywhere/chromium/rules.js:11
	const trivial_rule_to = "https:";
	^^^^^
	SyntaxError: Use of const in strict mode.
	    at Module._compile (module.js:439:25)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Module.require (module.js:364:17)
	    at require (module.js:380:17)
	    at Object.<anonymous> (/home/fuglede/https-everywhere/rewriter/rewriter.js:23:13)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)

If I remove `"use strict";` form `chromium/rules.js`, the issue becomes

	/home/fuglede/https-everywhere/chromium/rules.js:291
	      for (let target of resultSet.values()) {
		       ^^^^^^
	SyntaxError: Unexpected identifier
	    at Module._compile (module.js:439:25)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)
	    at Function.Module._load (module.js:312:12)
	    at Module.require (module.js:364:17)
	    at require (module.js:380:17)
	    at Object.<anonymous> (/home/fuglede/https-everywhere/rewriter/rewriter.js:23:13)
	    at Module._compile (module.js:456:26)
	    at Object.Module._extensions..js (module.js:474:10)
	    at Module.load (module.js:356:32)

**Comment by fuglede** [comment]
Ah, managed to make it work simply by upgrading `node`.
